development:
  adapter: postgresql
  encoding: unicode
  database: names_development
  host: localhost
  pool: 5
  username: postgres
  password: atlantis1

test:
  adapter: postgresql
  encoding: unicode
  database: names_test
  host: localhost
  pool: 5
  username: postgres
  password: atlantis1

